/**
 * Purpose: Central Game Registry — Single source of truth for all games in the application.
 *          Contains multilingual and age-based metadata for catalog filtering.
 * Module: Config
 * Folder: frontend/src/config
 */

import { AppLanguage, AppAge } from '../state/appLanguageStore';

export interface GameRegistryEntry {
  id: string;
  titleKey: string;
  descriptionKey: string;
  iconAsset: string;
  bgColor: string;
  gradientColors: readonly [string, string, string];
  bevelColor: string;
  badgeTag: string;
  navigatorRoute: string;
  routeParams?: Record<string, string>;
  supportedLanguages: AppLanguage[];
  minimumAge: AppAge;
  maximumAge: AppAge;
  ageGroups: readonly AppAge[];
}

export const GAME_REGISTRY: readonly GameRegistryEntry[] = [
  // ==========================================
  // AGE 5 GAMES (UNCHANGED)
  // ==========================================
  {
    id: 'alphabet_matching',
    titleKey: 'games.alphabetMatching.title',
    descriptionKey: 'games.alphabetMatching.description',
    iconAsset: '🔤',
    bgColor: '#3B82F6',
    gradientColors: ['#3B82F6', '#2563EB', '#1D4ED8'],
    bevelColor: '#1E40AF',
    badgeTag: 'A - Z',
    navigatorRoute: 'AlphabetMatchingModeSelection',
    supportedLanguages: ['en', 'hi', 'mr'],
    minimumAge: 5,
    maximumAge: 5,
    ageGroups: [5],
  },
  {
    id: 'capital_small_match',
    titleKey: 'games.capitalSmallMatch.title',
    descriptionKey: 'games.capitalSmallMatch.description',
    iconAsset: '🔠',
    bgColor: '#10B981',
    gradientColors: ['#10B981', '#059669', '#047857'],
    bevelColor: '#065F46',
    badgeTag: 'Aa - Zz',
    navigatorRoute: 'CapitalSmallMatchIntro',
    supportedLanguages: ['en'],
    minimumAge: 5,
    maximumAge: 5,
    ageGroups: [5],
  },
  {
    id: 'vowel_matra_match',
    titleKey: 'games.vowelMatraMatch.title',
    descriptionKey: 'games.vowelMatraMatch.description',
    iconAsset: '🕉️',
    bgColor: '#8B5CF6',
    gradientColors: ['#8B5CF6', '#7C3AED', '#6D28D9'],
    bevelColor: '#5B21B6',
    badgeTag: 'अ - क',
    navigatorRoute: 'VowelMatraMatchIntro',
    supportedLanguages: ['hi', 'mr'],
    minimumAge: 5,
    maximumAge: 5,
    ageGroups: [5],
  },
  {
    id: 'speech_letters',
    titleKey: 'games.speechLetters.title',
    descriptionKey: 'games.speechLetters.description',
    iconAsset: '🔤',
    bgColor: '#EC4899',
    gradientColors: ['#EC4899', '#DB2777', '#BE185D'],
    bevelColor: '#9D174D',
    badgeTag: '🔤 Letters',
    navigatorRoute: 'SpeechWordChallengeIntro',
    routeParams: { category: 'letters' },
    supportedLanguages: ['en', 'hi', 'mr'],
    minimumAge: 5,
    maximumAge: 5,
    ageGroups: [5],
  },
  {
    id: 'missing_letters',
    titleKey: 'games.missingLetters.title',
    descriptionKey: 'games.missingLetters.description',
    iconAsset: '🔤',
    bgColor: '#8B5CF6',
    gradientColors: ['#8B5CF6', '#7C3AED', '#6D28D9'],
    bevelColor: '#5B21B6',
    badgeTag: 'A _ C',
    navigatorRoute: 'MissingLettersIntro',
    supportedLanguages: ['en', 'hi', 'mr'],
    minimumAge: 5,
    maximumAge: 5,
    ageGroups: [5],
  },
  {
    id: 'missing_numbers',
    titleKey: 'games.missingNumbers.title',
    descriptionKey: 'games.missingNumbers.description',
    iconAsset: '🔢',
    bgColor: '#0284C7',
    gradientColors: ['#0284C7', '#0369A1', '#075985'],
    bevelColor: '#0C4A6E',
    badgeTag: '1 _ 3',
    navigatorRoute: 'MissingNumbersIntro',
    supportedLanguages: ['en', 'hi', 'mr'],
    minimumAge: 5,
    maximumAge: 5,
    ageGroups: [5],
  },
  {
    id: 'number_counting',
    titleKey: 'games.numberCounting.title',
    descriptionKey: 'games.numberCounting.description',
    iconAsset: '🍎',
    bgColor: '#10B981',
    gradientColors: ['#10B981', '#059669', '#047857'],
    bevelColor: '#064E3B',
    badgeTag: '1 2 3 🍎',
    navigatorRoute: 'NumberCountingIntro',
    supportedLanguages: ['en', 'hi', 'mr'],
    minimumAge: 5,
    maximumAge: 5,
    ageGroups: [5],
  },
  {
    id: 'put_in_order',
    titleKey: 'games.putInOrder.title',
    descriptionKey: 'games.putInOrder.description',
    iconAsset: '🧩',
    bgColor: '#F59E0B',
    gradientColors: ['#F59E0B', '#D97706', '#B45309'],
    bevelColor: '#78350F',
    badgeTag: '1 ➔ 2 ➔ 3',
    navigatorRoute: 'PutInOrderIntro',
    supportedLanguages: ['en', 'hi', 'mr'],
    minimumAge: 5,
    maximumAge: 5,
    ageGroups: [5],
  },

  // ==========================================
  // AGE 6 GAMES (VOCABULARY CATEGORIES)
  // ==========================================
  {
    id: 'speech_animals',
    titleKey: 'games.speechAnimals.title',
    descriptionKey: 'games.speechAnimals.description',
    iconAsset: '🐾',
    bgColor: '#F59E0B',
    gradientColors: ['#F59E0B', '#D97706', '#B45309'],
    bevelColor: '#92400E',
    badgeTag: '🐾 Animals',
    navigatorRoute: 'SpeechWordChallengeIntro',
    routeParams: { category: 'animals' },
    supportedLanguages: ['en', 'hi', 'mr'],
    minimumAge: 6,
    maximumAge: 7,
    ageGroups: [6, 7],
  },
  {
    id: 'speech_fruits_vegetables',
    titleKey: 'games.speechFruits.title',
    descriptionKey: 'games.speechFruits.description',
    iconAsset: '🍎',
    bgColor: '#10B981',
    gradientColors: ['#10B981', '#059669', '#047857'],
    bevelColor: '#065F46',
    badgeTag: '🍎 Fruits & Veg',
    navigatorRoute: 'SpeechWordChallengeIntro',
    routeParams: { category: 'fruits' },
    supportedLanguages: ['en', 'hi', 'mr'],
    minimumAge: 6,
    maximumAge: 7,
    ageGroups: [6, 7],
  },
  {
    id: 'speech_everyday_nature',
    titleKey: 'games.speechEveryday.title',
    descriptionKey: 'games.speechEveryday.description',
    iconAsset: '🌳',
    bgColor: '#6366F1',
    gradientColors: ['#6366F1', '#4F46E5', '#4338CA'],
    bevelColor: '#3730A3',
    badgeTag: '🌳 Nature',
    navigatorRoute: 'SpeechWordChallengeIntro',
    routeParams: { category: 'nature' },
    supportedLanguages: ['en', 'hi', 'mr'],
    minimumAge: 6,
    maximumAge: 7,
    ageGroups: [6, 7],
  },
  {
    id: 'language_pair_match',
    titleKey: 'games.languagePairMatch.title',
    descriptionKey: 'games.languagePairMatch.description',
    iconAsset: '🧩',
    bgColor: '#EC4899',
    gradientColors: ['#EC4899', '#DB2777', '#BE185D'],
    bevelColor: '#9D174D',
    badgeTag: '🧩 Word Match',
    navigatorRoute: 'LanguagePairMatchIntro',
    supportedLanguages: ['en', 'hi', 'mr'],
    minimumAge: 6,
    maximumAge: 6,
    ageGroups: [6],
  },

  // ==========================================
  // AGE-ADAPTIVE GAMES (AGES 5, 6, 7)
  // ==========================================
  {
    id: 'colour_challenge',
    titleKey: 'games.colourChallenge.title',
    descriptionKey: 'games.colourChallenge.description',
    iconAsset: '🎨',
    bgColor: '#F59E0B',
    gradientColors: ['#F59E0B', '#D97706', '#B45309'],
    bevelColor: '#92400E',
    badgeTag: '🎨 Colours',
    navigatorRoute: 'ColourChallengeIntro',
    supportedLanguages: ['en', 'hi', 'mr'],
    minimumAge: 5,
    maximumAge: 7,
    ageGroups: [5, 6, 7],
  },
  {
    id: 'shape_challenge',
    titleKey: 'games.shapeChallenge.title',
    descriptionKey: 'games.shapeChallenge.description',
    iconAsset: '📐',
    bgColor: '#3B82F6',
    gradientColors: ['#3B82F6', '#2563EB', '#1D4ED8'],
    bevelColor: '#1E40AF',
    badgeTag: '📐 Shapes',
    navigatorRoute: 'ShapeChallengeIntro',
    supportedLanguages: ['en', 'hi', 'mr'],
    minimumAge: 5,
    maximumAge: 7,
    ageGroups: [5, 6, 7],
  },
  {
    id: 'guess_the_shape',
    titleKey: 'games.guessTheShape.title',
    descriptionKey: 'games.guessTheShape.description',
    iconAsset: '🔷',
    bgColor: '#4F46E5',
    gradientColors: ['#6366F1', '#4F46E5', '#3730A3'],
    bevelColor: '#312E81',
    badgeTag: '🔷 Shapes',
    navigatorRoute: 'GuessTheShapeIntro',
    supportedLanguages: ['en', 'hi', 'mr'],
    minimumAge: 6,
    maximumAge: 7,
    ageGroups: [6, 7],
  },
  {
    id: 'missing_letter_words',
    titleKey: 'games.missingLetterWords.title',
    descriptionKey: 'games.missingLetterWords.description',
    iconAsset: '🔤',
    bgColor: '#F59E0B',
    gradientColors: ['#F59E0B', '#D97706', '#B45309'],
    bevelColor: '#92400E',
    badgeTag: 'C _ T',
    navigatorRoute: 'MissingLetterWordsIntro',
    supportedLanguages: ['en', 'hi', 'mr'],
    minimumAge: 6,
    maximumAge: 7,
    ageGroups: [6, 7],
  },
  {
    id: 'find_the_correct_word',
    titleKey: 'games.findTheCorrectWord.title',
    descriptionKey: 'games.findTheCorrectWord.description',
    iconAsset: '📝',
    bgColor: '#059669',
    gradientColors: ['#10B981', '#059669', '#047857'],
    bevelColor: '#064E3B',
    badgeTag: 'CAT ✓',
    navigatorRoute: 'FindTheCorrectWordIntro',
    supportedLanguages: ['en', 'hi', 'mr'],
    minimumAge: 6,
    maximumAge: 7,
    ageGroups: [6, 7],
  },
  {
    id: 'letter_tracing',
    titleKey: 'games.letterTracing.title',
    descriptionKey: 'games.letterTracing.description',
    iconAsset: '✍️',
    bgColor: '#10B981',
    gradientColors: ['#10B981', '#059669', '#047857'],
    bevelColor: '#065F46',
    badgeTag: '✍️ Tracing',
    navigatorRoute: 'LetterTracingIntro',
    supportedLanguages: ['en', 'hi', 'mr'],
    minimumAge: 5,
    maximumAge: 7,
    ageGroups: [5, 6, 7],
  },

  // ==========================================
  // AGE 6 MATHEMATICS GAMES
  // ==========================================
  {
    id: 'addition',
    titleKey: 'games.addition.title',
    descriptionKey: 'games.addition.description',
    iconAsset: '➕',
    bgColor: '#3B82F6',
    gradientColors: ['#3B82F6', '#2563EB', '#1D4ED8'],
    bevelColor: '#1E40AF',
    badgeTag: '➕ Add',
    navigatorRoute: 'MathChallengeIntro',
    routeParams: { operation: 'addition' },
    supportedLanguages: ['en', 'hi', 'mr'],
    minimumAge: 6,
    maximumAge: 6,
    ageGroups: [6],
  },
  {
    id: 'subtraction',
    titleKey: 'games.subtraction.title',
    descriptionKey: 'games.subtraction.description',
    iconAsset: '➖',
    bgColor: '#EC4899',
    gradientColors: ['#EC4899', '#DB2777', '#BE185D'],
    bevelColor: '#9D174D',
    badgeTag: '➖ Subtract',
    navigatorRoute: 'MathChallengeIntro',
    routeParams: { operation: 'subtraction' },
    supportedLanguages: ['en', 'hi', 'mr'],
    minimumAge: 6,
    maximumAge: 6,
    ageGroups: [6],
  },

  // ==========================================
  // AGE 7 MATHEMATICS GAMES
  // ==========================================
  {
    id: 'bigger_addition',
    titleKey: 'games.biggerAddition.title',
    descriptionKey: 'games.biggerAddition.description',
    iconAsset: '➕',
    bgColor: '#F59E0B',
    gradientColors: ['#F59E0B', '#D97706', '#B45309'],
    bevelColor: '#92400E',
    badgeTag: '➕ Big Add',
    navigatorRoute: 'MathChallengeIntro',
    routeParams: { operation: 'bigger_addition' },
    supportedLanguages: ['en', 'hi', 'mr'],
    minimumAge: 7,
    maximumAge: 7,
    ageGroups: [7],
  },
  {
    id: 'multiplication',
    titleKey: 'games.multiplication.title',
    descriptionKey: 'games.multiplication.description',
    iconAsset: '✖️',
    bgColor: '#8B5CF6',
    gradientColors: ['#8B5CF6', '#7C3AED', '#6D28D9'],
    bevelColor: '#5B21B6',
    badgeTag: '✖️ Multiply',
    navigatorRoute: 'MathChallengeIntro',
    routeParams: { operation: 'multiplication' },
    supportedLanguages: ['en', 'hi', 'mr'],
    minimumAge: 7,
    maximumAge: 7,
    ageGroups: [7],
  },
  {
    id: 'division',
    titleKey: 'games.division.title',
    descriptionKey: 'games.division.description',
    iconAsset: '➗',
    bgColor: '#10B981',
    gradientColors: ['#10B981', '#059669', '#047857'],
    bevelColor: '#065F46',
    badgeTag: '➗ Divide',
    navigatorRoute: 'MathChallengeIntro',
    routeParams: { operation: 'division' },
    supportedLanguages: ['en', 'hi', 'mr'],
    minimumAge: 7,
    maximumAge: 7,
    ageGroups: [7],
  },

  // ==========================================
  // AGE 6 APTITUDE / LOGICAL THINKING GAMES
  // ==========================================
  {
    id: 'pattern_match',
    titleKey: 'games.patternMatch.title',
    descriptionKey: 'games.patternMatch.description',
    iconAsset: '🧩',
    bgColor: '#8B5CF6',
    gradientColors: ['#8B5CF6', '#7C3AED', '#6D28D9'],
    bevelColor: '#5B21B6',
    badgeTag: '🧩 Patterns',
    navigatorRoute: 'AptitudeChallengeIntro',
    routeParams: { gameType: 'pattern_match' },
    supportedLanguages: ['en', 'hi', 'mr'],
    minimumAge: 6,
    maximumAge: 6,
    ageGroups: [6],
  },
  {
    id: 'bigger_smaller',
    titleKey: 'games.biggerSmaller.title',
    descriptionKey: 'games.biggerSmaller.description',
    iconAsset: '⚖️',
    bgColor: '#3B82F6',
    gradientColors: ['#3B82F6', '#2563EB', '#1D4ED8'],
    bevelColor: '#1E40AF',
    badgeTag: '⚖️ Compare',
    navigatorRoute: 'AptitudeChallengeIntro',
    routeParams: { gameType: 'bigger_smaller' },
    supportedLanguages: ['en', 'hi', 'mr'],
    minimumAge: 6,
    maximumAge: 6,
    ageGroups: [6],
  },
  {
    id: 'what_comes_next',
    titleKey: 'games.whatComesNext.title',
    descriptionKey: 'games.whatComesNext.description',
    iconAsset: '➡️',
    bgColor: '#10B981',
    gradientColors: ['#10B981', '#059669', '#047857'],
    bevelColor: '#065F46',
    badgeTag: '➡️ Next',
    navigatorRoute: 'AptitudeChallengeIntro',
    routeParams: { gameType: 'what_comes_next' },
    supportedLanguages: ['en', 'hi', 'mr'],
    minimumAge: 6,
    maximumAge: 6,
    ageGroups: [6],
  },

  // ==========================================
  // AGE 7 APTITUDE / LOGICAL THINKING GAMES
  // ==========================================
  {
    id: 'number_pattern',
    titleKey: 'games.numberPattern.title',
    descriptionKey: 'games.numberPattern.description',
    iconAsset: '🔢',
    bgColor: '#F59E0B',
    gradientColors: ['#F59E0B', '#D97706', '#B45309'],
    bevelColor: '#92400E',
    badgeTag: '🔢 Sequences',
    navigatorRoute: 'AptitudeChallengeIntro',
    routeParams: { gameType: 'number_pattern' },
    supportedLanguages: ['en', 'hi', 'mr'],
    minimumAge: 7,
    maximumAge: 7,
    ageGroups: [7],
  },
  {
    id: 'odd_one_out',
    titleKey: 'games.oddOneOut.title',
    descriptionKey: 'games.oddOneOut.description',
    iconAsset: '🔍',
    bgColor: '#EC4899',
    gradientColors: ['#EC4899', '#DB2777', '#BE185D'],
    bevelColor: '#9D174D',
    badgeTag: '🔍 Odd One',
    navigatorRoute: 'AptitudeChallengeIntro',
    routeParams: { gameType: 'odd_one_out' },
    supportedLanguages: ['en', 'hi', 'mr'],
    minimumAge: 7,
    maximumAge: 7,
    ageGroups: [7],
  },
  {
    id: 'odd_word_out',
    titleKey: 'games.oddWordOut.title',
    descriptionKey: 'games.oddWordOut.description',
    iconAsset: '🎯',
    bgColor: '#4F46E5',
    gradientColors: ['#6366F1', '#4F46E5', '#3730A3'],
    bevelColor: '#312E81',
    badgeTag: '🎯 Odd Word',
    navigatorRoute: 'OddWordOutIntro',
    supportedLanguages: ['en', 'hi', 'mr'],
    minimumAge: 7,
    maximumAge: 7,
    ageGroups: [7],
  },
  {
    id: 'logical_sequence',
    titleKey: 'games.logicalSequence.title',
    descriptionKey: 'games.logicalSequence.description',
    iconAsset: '⏳',
    bgColor: '#06B6D4',
    gradientColors: ['#06B6D4', '#0891B2', '#0E7490'],
    bevelColor: '#155E75',
    badgeTag: '⏳ Sequence',
    navigatorRoute: 'AptitudeChallengeIntro',
    routeParams: { gameType: 'logical_sequence' },
    supportedLanguages: ['en', 'hi', 'mr'],
    minimumAge: 7,
    maximumAge: 7,
    ageGroups: [7],
  },
  {
    id: 'visual_reasoning',
    titleKey: 'games.visualReasoning.title',
    descriptionKey: 'games.visualReasoning.description',
    iconAsset: '🧠',
    bgColor: '#6366F1',
    gradientColors: ['#6366F1', '#4F46E5', '#4338CA'],
    bevelColor: '#3730A3',
    badgeTag: '🧠 Visual',
    navigatorRoute: 'AptitudeChallengeIntro',
    routeParams: { gameType: 'visual_reasoning' },
    supportedLanguages: ['en', 'hi', 'mr'],
    minimumAge: 7,
    maximumAge: 7,
    ageGroups: [7],
  },

  // ==========================================
  // AGE 6 BASIC GRAMMAR GAMES
  // ==========================================
  {
    id: 'noun_or_verb',
    titleKey: 'games.nounOrVerb.title',
    descriptionKey: 'games.nounOrVerb.description',
    iconAsset: '📝',
    bgColor: '#3B82F6',
    gradientColors: ['#3B82F6', '#2563EB', '#1D4ED8'],
    bevelColor: '#1E40AF',
    badgeTag: '📝 Words',
    navigatorRoute: 'GrammarChallengeIntro',
    routeParams: { topic: 'noun_or_verb' },
    supportedLanguages: ['en', 'hi', 'mr'],
    minimumAge: 6,
    maximumAge: 6,
    ageGroups: [6],
  },
  {
    id: 'singular_or_plural',
    titleKey: 'games.singularOrPlural.title',
    descriptionKey: 'games.singularOrPlural.description',
    iconAsset: '🔢',
    bgColor: '#10B981',
    gradientColors: ['#10B981', '#059669', '#047857'],
    bevelColor: '#065F46',
    badgeTag: '🔢 One/Many',
    navigatorRoute: 'GrammarChallengeIntro',
    routeParams: { topic: 'singular_or_plural' },
    supportedLanguages: ['en', 'hi', 'mr'],
    minimumAge: 6,
    maximumAge: 6,
    ageGroups: [6],
  },
  {
    id: 'complete_the_sentence',
    titleKey: 'games.completeSentence.title',
    descriptionKey: 'games.completeSentence.description',
    iconAsset: '✏️',
    bgColor: '#8B5CF6',
    gradientColors: ['#8B5CF6', '#7C3AED', '#6D28D9'],
    bevelColor: '#5B21B6',
    badgeTag: '✏️ Fill In',
    navigatorRoute: 'GrammarChallengeIntro',
    routeParams: { topic: 'complete_the_sentence' },
    supportedLanguages: ['en', 'hi', 'mr'],
    minimumAge: 6,
    maximumAge: 6,
    ageGroups: [6],
  },

  // ==========================================
  // AGE 7 BASIC GRAMMAR GAMES
  // ==========================================
  {
    id: 'articles_determiners',
    titleKey: 'games.articlesDeterminers.title',
    descriptionKey: 'games.articlesDeterminers.description',
    iconAsset: '🔤',
    bgColor: '#F59E0B',
    gradientColors: ['#F59E0B', '#D97706', '#B45309'],
    bevelColor: '#92400E',
    badgeTag: '🔤 Articles',
    navigatorRoute: 'GrammarChallengeIntro',
    routeParams: { topic: 'articles_determiners' },
    supportedLanguages: ['en', 'hi', 'mr'],
    minimumAge: 7,
    maximumAge: 7,
    ageGroups: [7],
  },
  {
    id: 'pronouns',
    titleKey: 'games.pronouns.title',
    descriptionKey: 'games.pronouns.description',
    iconAsset: '👤',
    bgColor: '#EC4899',
    gradientColors: ['#EC4899', '#DB2777', '#BE185D'],
    bevelColor: '#9D174D',
    badgeTag: '👤 Pronouns',
    navigatorRoute: 'GrammarChallengeIntro',
    routeParams: { topic: 'pronouns' },
    supportedLanguages: ['en', 'hi', 'mr'],
    minimumAge: 7,
    maximumAge: 7,
    ageGroups: [7],
  },
  {
    id: 'prepositions',
    titleKey: 'games.prepositions.title',
    descriptionKey: 'games.prepositions.description',
    iconAsset: '📍',
    bgColor: '#06B6D4',
    gradientColors: ['#06B6D4', '#0891B2', '#0E7490'],
    bevelColor: '#155E75',
    badgeTag: '📍 Position',
    navigatorRoute: 'GrammarChallengeIntro',
    routeParams: { topic: 'prepositions' },
    supportedLanguages: ['en', 'hi', 'mr'],
    minimumAge: 7,
    maximumAge: 7,
    ageGroups: [7],
  },
  {
    id: 'basic_tenses',
    titleKey: 'games.basicTenses.title',
    descriptionKey: 'games.basicTenses.description',
    iconAsset: '⏱️',
    bgColor: '#6366F1',
    gradientColors: ['#6366F1', '#4F46E5', '#4338CA'],
    bevelColor: '#3730A3',
    badgeTag: '⏱️ Tenses',
    navigatorRoute: 'GrammarChallengeIntro',
    routeParams: { topic: 'basic_tenses' },
    supportedLanguages: ['en', 'hi', 'mr'],
    minimumAge: 7,
    maximumAge: 7,
    ageGroups: [7],
  },
  {
    id: 'sentence_correction',
    titleKey: 'games.sentenceCorrection.title',
    descriptionKey: 'games.sentenceCorrection.description',
    iconAsset: '✔️',
    bgColor: '#059669',
    gradientColors: ['#10B981', '#059669', '#047857'],
    bevelColor: '#065F46',
    badgeTag: '✔️ Fix It',
    navigatorRoute: 'GrammarChallengeIntro',
    routeParams: { topic: 'sentence_correction' },
    supportedLanguages: ['en', 'hi', 'mr'],
    minimumAge: 7,
    maximumAge: 7,
    ageGroups: [7],
  },
] as const;
